apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: connme-ingress-tcp-patch
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/prod/mow/www.connme.ru/ingress-port-forward
  prune: false
  patches:
  - patch: |
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: nginx-ingress-tcp-microk8s-conf
        namespace: ingress
      data:
        "7681": "www-connme-ru/chat-service:7681"
    target:
      kind: ConfigMap
      name: nginx-ingress-tcp-microk8s-conf
      namespace: ingress
