resources:
- https://github.com/cert-manager/cert-manager/releases/download/v1.19.2/cert-manager.yaml
- issuer-prod.yaml
- issuer-staging.yaml

patches:
- path: patch-prod.yaml
- path: patch-staging.yaml
