apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-redirect-ingress
  annotations:
    nginx.ingress.kubernetes.io/permanent-redirect: "https://www.smotra.net"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - smotra.net
    secretName: https-secret-redirect
  rules:
  - host: smotra.net
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/permanent-redirect: "https://stub.smotra.net"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - www.smotra.net
    secretName: https-secret
  rules:
  - host: www.smotra.net
